# Generated by Django 2.2.7 on 2019-12-16 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Sai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('mob', models.IntegerField()),
                ('mail', models.EmailField(max_length=20)),
                ('agee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inside.Age')),
            ],
        ),
    ]
