# Generated by Django 2.2.7 on 2019-12-17 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0002_sai_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='sai',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='img'),
            preserve_default=False,
        ),
    ]
