# Generated by Django 2.2.7 on 2019-12-19 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0004_sai_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='sai',
            name='about',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
